<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>InfoPanel</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Svg.Skia" Version="3.2.1" />
    <PackageReference Include="Topten.RichTextKit" Version="0.4.167" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfoPanel.Core\InfoPanel.Core.csproj" />
    <ProjectReference Include="..\InfoPanel.Plugins\InfoPanel.Plugins.csproj" />
    <ProjectReference Include="..\InfoPanel.Plugins.Graphics\InfoPanel.Plugins.Graphics.csproj" />
  </ItemGroup>

</Project>
